[env:fake-battery]
platform = atmelsam
board = fake-battery
framework = arduino
board_build.variants_dir = custom_variants
upload_protocol = jlink
debug_tool = jlink
build_flags =
    -D__SAMD21E18A__